repos:
  - repo: local
    hooks:
      - id: local-ruff-check
        name: ruff check
        entry: uv run ruff check --fix --exit-non-zero-on-fix
        require_serial: true
        language: unsupported
        types: [python]

      - id: local-ruff-format
        name: ruff format
        entry: uv run ruff format --exit-non-zero-on-format
        require_serial: true
        language: unsupported
        types: [python]

      - id: local-ty
        name: ty check
        entry: uv run ty check fasty
        require_serial: true
        language: unsupported
        pass_filenames: false
