[project]
name = "fasty"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "alembic",
    "databases[postgresql]",
    "fastapi[standard]",
    "gunicorn==24.0.0",
    "psycopg2",
    "pydantic-settings",
    "pydantic",
    "python-dotenv",
    "python-jose",
    "uvicorn",
]

[dependency-groups]
dev = [
    "bandit",
    "databases[aiosqlite,postgresql]",
    "faker",
    "httpx",
    "pytest",
    "pytest-asyncio",
    "pytest-cov",
    "pytest-env",
    "pytest-forked",
    "pytest-xdist",
    "requests",
    "ruff",
    "schemathesis",
    "ty",
]

[tool.pytest_env]
DB_ENGINE="sqlite+aiosqlite"
DB_HOST="localhost"
DB_NAME="test_fasty"
DB_PASSWORD="password"
DB_USER="fasty"
DEBUG="True"

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
