[tool.poetry]
name = "fasty"
version = "0.1.0"
description = ""
authors = ["Chris Wright <cwright@twigeducation.com>"]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.65.2"
python-jose = "^3.1.0"
uvicorn = "^0.14.0"
gunicorn = "^20.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=1.1.6"]
build-backend = "poetry.masonry.api"
